### ISSUE TITLE
Streching of small images

### ISSUE THREAD

**Issue by nickhamze** [sortastupid/rentsdue#4]
Take a look at this post:
https://sortaquirky.com/post/188111170012/im-back-on-tumblr-after-about-8-years-away

When a small image is loaded it gets stretched due to this line of CSS. I think we just need to take out the 100% of the following rule to fix it. 

.post img, .post blockquote figure {
    width: 100%; 
}

We also need to decide what to do with smaller images. Do you center them or what?

**Comment by nickhamze** [comment]
Actually maybe just removing that won't work. On the test site it causes things to go crazy. I'm sure you'll find a different solution. Basically all I want to make sure is images aren't blown up.

**Comment by nickhamze** [comment]
On a related note if you look at this post from my site (https://sortaquirky.com/post/188157302482/i-found-this-article-in-the-april-1999-issues-of). We need to figure out if we want to center photosets (I think we probably should). It looks like the default size is 700px so we either need to center it or load a larger size that fills up the container.

**Comment by ariccioppox** [comment]
**ISSUES FIXED**

_Images:_ Changed `.post img(...){width:100%}` to `.post img(...){max-width:100%; height:auto}`
_Photosets:_ Added [PXU Photoset](https://github.com/PixelUnion/Extended-Tumblr-Photoset) to load responsive larger images for photosets.

Closing this issue, please reopen if the reported behaviors persists.
